Testing JUnit reporter

diff --git a/.github/workflows/basic_ci.yaml b/.github/workflows/basic_ci.yaml
--- a/.github/workflows/basic_ci.yaml
+++ b/.github/workflows/basic_ci.yaml
@@ -114,4 +114,14 @@ jobs:
         run: |
           value=`ls`
           echo $value
+      
+      # Test JUnit test reporter
+      # https://github.com/marketplace/actions/test-reporter
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JUnit Report            # Name of the check run which will be created
+          path: pytest-results-*.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
         
